version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
      - chmod +x scripts/*.sh

  build:
    commands:
      - echo "Build phase - skipping actual build for this static app"

  post_build:
    commands:
      - echo "Build completed on `date`"
