version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - chmod +x scripts/*.sh

artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/**
