version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: my-web-app/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: my-web-app/scripts/start_server.sh
      timeout: 300
      runas: root
