version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-web-app

hooks:
  BeforeInstall:
    - location: my-web-app/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: my-web-app/scripts/start_server.sh
      timeout: 300
      runas: ec2-user
